### ISSUE TITLE
Allow Arduino Version as a parameter

### ISSUE THREAD

**Issue by chatelao** [adafruit/travis-ci-arduino#4] opened 2015-07-30 18:39 UTC
To provide some regression testing, a compilation with a new and an old version should be possible to recognize fails due to dependency changes.

**Comment by toddtreece** [comment] 2015-07-30 21:04
@chatelao are you referring to changing between 1.0.x to 1.6.x versions? or mainly between 1.6.x versions?

**Comment by chatelao** [comment] 2015-07-31 14:44
Whatever version will come in the future. I would like to set the version myself, something like:
- build_platform uno 1.6.4
- build_platform uno 1.6.5
- build_platform uno latest

In case a new version fails, I would like to prove that an old version worked fine and find the difference in the Arduino package.

**Comment by toddtreece** [comment] 2015-07-31 15:37
I think this is probably overkill for our purposes since we are mostly concerned with testing current stable version of the IDE. Arduino should be testing IDE regressions in their own repo, and it would add a lot of extra runtime to check multiple IDE versions in our tests.

I'm going to close this one since we aren't going to be adding it, but feel free to issue a pull request if you end up implementing it and we can look at merging it in.

Thanks!

**Closed by toddtreece** 2015-07-31 15:37 UTC

**Comment by chatelao** [comment] 2015-08-01 06:29
Thanks for the fast feedback.
